# Generated by Django 5.0.6 on 2024-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_storage',
            field=models.IntegerField(default=52428800),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_storage',
            field=models.IntegerField(default=0),
        ),
    ]
