# Generated by Django 5.0.6 on 2024-06-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_within', to='mainapp.folder'),
        ),
    ]
